//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeReviewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AllReviews
    {
        public string EmployeeName { get; set; }
        public string ReviewerName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Summary { get; set; }
        public Nullable<bool> EmployeeSigned { get; set; }
        public Nullable<bool> EmployerSigned { get; set; }
        public string ReviewType { get; set; }
        public int ReviewId { get; set; }
    }
}
